In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter("ignore")
import seaborn as sns

In [2]:
df = pd.read_csv('learningSet.csv')
df

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,...,0.0,0,L,4,E,X,X,X,39.0,C
1,9401,BOA,1,CA,91326,,,5202,0,,...,0.0,0,L,2,G,X,X,X,1.0,A
2,9001,AMH,1,NC,27017,,,0,0,,...,0.0,1,L,4,E,X,X,X,60.0,C
3,8701,BRY,0,CA,95953,,,2801,0,,...,0.0,1,L,4,E,X,X,X,41.0,C
4,8601,,0,FL,33176,,,2001,0,X,...,0.0,1,L,2,F,X,X,X,26.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,9601,ASE,1,AK,99504,,,0,0,,...,0.0,0,L,1,G,X,X,X,12.0,C
95408,9601,DCD,1,TX,77379,,,5001,0,,...,0.0,1,L,1,F,X,X,X,2.0,A
95409,9501,MBC,1,MI,48910,,,3801,0,,...,0.0,1,L,3,E,X,X,X,34.0,B
95410,8601,PRV,0,CA,91320,,,4005,0,X,...,18.0,1,L,4,F,X,X,X,11.0,A
95411,8801,MCC,2,NC,28409,,,1801,0,X,...,0.0,1,L,1,G,C,1,C,12.0,C

In [3]:
numerical= df.select_dtypes(np.number)
numerical.head()

,ODATEDW,TCODE,DOB,AGE,NUMCHLD,INCOME,WEALTH1,HIT,MBCRAFT,MBGARDEN,...,FISTDATE,NEXTDATE,TIMELAG,AVGGIFT,CONTROLN,TARGET_B,TARGET_D,HPHONE_D,RFA_2F,CLUSTER2
0,8901,0,3712,60.0,NaN,NaN,NaN,0,NaN,NaN,...,8911,9003.0,4.0,7.741935,95515,0,0.0,0,4,39.0
1,9401,1,5202,46.0,1.0,6.0,9.0,16,0.0,0.0,...,9310,9504.0,18.0,15.666667,148535,0,0.0,0,2,1.0
2,9001,1,0,NaN,NaN,3.0,1.0,2,0.0,0.0,...,9001,9101.0,12.0,7.481481,15078,0,0.0,1,4,60.0
3,8701,0,2801,70.0,NaN,1.0,4.0,2,0.0,0.0,...,8702,8711.0,9.0,6.812500,172556,0,0.0,1,4,41.0
4,8601,0,2001,78.0,1.0,3.0,2.0,60,1.0,0.0,...,7903,8005.0,14.0,6.864865,7112,0,0.0,1,2,26.0

In [4]:
pd.set_option('display.max_rows', None)
numerical.isna().sum()

ODATEDW         0
TCODE           0
DOB             0
AGE         23665
NUMCHLD     83026
INCOME      21286
WEALTH1     44732
HIT             0
MBCRAFT     52854
MBGARDEN    52854
MBBOOKS     52854
MBCOLECT    52914
MAGFAML     52854
MAGFEM      52854
MAGMALE     52854
PUBGARDN    52854
PUBCULIN    52854
PUBHLTH     52854
PUBDOITY    52854
PUBNEWFN    52854
PUBPHOTO    52854
PUBOPP      52854
MALEMILI        0
MALEVET         0
VIETVETS        0
WWIIVETS        0
LOCALGOV        0
STATEGOV        0
FEDGOV          0
WEALTH2     43823
POP901          0
POP902          0
POP903          0
POP90C1         0
POP90C2         0
POP90C3         0
POP90C4         0
POP90C5         0
ETH1            0
ETH2            0
ETH3            0
ETH4            0
ETH5            0
ETH6            0
ETH7            0
ETH8            0
ETH9            0
ETH10           0
ETH11           0
ETH12           0
ETH13           0
ETH14           0
ETH15           0
ETH16           0
AGE901          0
AGE902          0
AGE903          0
AGE904          0
AGE905          0
AGE906          0
AGE907          0
CHIL1           0
CHIL2           0
CHIL3           0
AGEC1           0
AGEC2           0
AGEC3           0
AGEC4           0
AGEC5           0
AGEC6           0
AGEC7           0
CHILC1          0
CHILC2          0
CHILC3          0
CHILC4          0
CHILC5          0
HHAGE1          0
HHAGE2          0
HHAGE3          0
HHN1            0
HHN2            0
HHN3            0
HHN4            0
HHN5            0
HHN6            0
MARR1           0
MARR2           0
MARR3           0
MARR4           0
HHP1            0
HHP2            0
DW1             0
DW2             0
DW3             0
DW4             0
DW5             0
DW6             0
DW7             0
DW8             0
DW9             0
HV1             0
HV2             0
HV3             0
HV4             0
HU1             0
HU2             0
HU3             0
HU4             0
HU5             0
HHD1            0
HHD2            0
HHD3            0
HHD4            0
HHD5            0
HHD6            0
HHD7            0
HHD8            0
HHD9            0
HHD10           0
HHD11           0
HHD12           0
ETHC1           0
ETHC2           0
ETHC3           0
ETHC4           0
ETHC5           0
ETHC6           0
HVP1            0
HVP2            0
HVP3            0
HVP4            0
HVP5            0
HVP6            0
HUR1            0
HUR2            0
RHP1            0
RHP2            0
RHP3            0
RHP4            0
HUPA1           0
HUPA2           0
HUPA3           0
HUPA4           0
HUPA5           0
HUPA6           0
HUPA7           0
RP1             0
RP2             0
RP3             0
RP4             0
MSA           132
ADI           132
DMA           132
IC1             0
IC2             0
IC3             0
IC4             0
IC5             0
IC6             0
IC7             0
IC8             0
IC9             0
IC10            0
IC11            0
IC12            0
IC13            0
IC14            0
IC15            0
IC16            0
IC17            0
IC18            0
IC19            0
IC20            0
IC21            0
IC22            0
IC23            0
HHAS1           0
HHAS2           0
HHAS3           0
HHAS4           0
MC1             0
MC2             0
MC3             0
TPE1            0
TPE2            0
TPE3            0
TPE4            0
TPE5            0
TPE6            0
TPE7            0
TPE8            0
TPE9            0
PEC1            0
PEC2            0
TPE10           0
TPE11           0
TPE12           0
TPE13           0
LFC1            0
LFC2            0
LFC3            0
LFC4            0
LFC5            0
LFC6            0
LFC7            0
LFC8            0
LFC9            0
LFC10           0
OCC1            0
OCC2            0
OCC3            0
OCC4            0
OCC5            0
OCC6            0
OCC7            0
OCC8            0
OCC9            0
OCC10           0
OCC11           0
OCC12           0
OCC13           0
EIC1            0
EIC2            0
EIC3            0
EIC4            0
EIC5            0
EIC6            0
EIC7            0
EIC8            0
EIC9            0
EIC10           0
EIC11           0
EIC12           0
EIC13           0
EIC14           0
EIC15           0
EIC16           0
OEDC1           0
OEDC2           0
OEDC3           0
OEDC4           0
OEDC5           0
OEDC6           0
OEDC7           0
EC1             0
EC2             0
EC3             0
EC4             0
EC5             0
EC6             0
EC7             0
EC8             0
SEC1            0
SEC2            0
SEC3            0
SEC4            0
SEC5            0
AFC1            0
AFC2            0
AFC3            0
AFC4            0
AFC5            0
AFC6            0
VC1             0
VC2             0
VC3             0
VC4             0
ANC1            0
ANC2            0
ANC3            0
ANC4            0
ANC5            0
ANC6            0
ANC7            0
ANC8            0
ANC9            0
ANC10           0
ANC11           0
ANC12           0
ANC13           0
ANC14           0
ANC15           0
POBC1           0
POBC2           0
LSC1            0
LSC2            0
LSC3            0
LSC4            0
VOC1            0
VOC2            0
VOC3            0
HC1             0
HC2             0
HC3             0
HC4             0
HC5             0
HC6             0
HC7             0
HC8             0
HC9             0
HC10            0
HC11            0
HC12            0
HC13            0
HC14            0
HC15            0
HC16            0
HC17            0
HC18            0
HC19            0
HC20            0
HC21            0
MHUC1           0
MHUC2           0
AC1             0
AC2             0
ADATE_2         0
ADATE_3      1950
ADATE_4      2191
ADATE_5     33590
ADATE_6      3557
ADATE_7      8874
ADATE_8      3511
ADATE_9     11245
ADATE_10    32748
ADATE_11    10422
ADATE_12     8923
ADATE_13    40219
ADATE_14    18867
ADATE_15    65477
ADATE_16    20364
ADATE_17    27650
ADATE_18    21263
ADATE_19    24480
ADATE_20    50200
ADATE_21    35212
ADATE_22    25648
ADATE_23    56270
ADATE_24    36973
CARDPROM        0
MAXADATE        0
NUMPROM         0
CARDPM12        0
NUMPRM12        0
RDATE_3     95170
RDATE_4     95131
RDATE_5     95403
RDATE_6     94636
RDATE_7     86517
RDATE_8     73940
RDATE_9     78678
RDATE_10    84951
RDATE_11    80672
RDATE_12    69712
RDATE_13    83162
RDATE_14    72095
RDATE_15    88150
RDATE_16    68418
RDATE_17    86011
RDATE_18    75634
RDATE_19    79535
RDATE_20    87524
RDATE_21    85899
RDATE_22    74539
RDATE_23    87553
RDATE_24    77674
RAMNT_3     95170
RAMNT_4     95131
RAMNT_5     95403
RAMNT_6     94636
RAMNT_7     86517
RAMNT_8     73940
RAMNT_9     78678
RAMNT_10    84951
RAMNT_11    80672
RAMNT_12    69712
RAMNT_13    83162
RAMNT_14    72095
RAMNT_15    88150
RAMNT_16    68418
RAMNT_17    86011
RAMNT_18    75634
RAMNT_19    79535
RAMNT_20    87524
RAMNT_21    85899
RAMNT_22    74539
RAMNT_23    87553
RAMNT_24    77674
RAMNTALL        0
NGIFTALL        0
CARDGIFT        0
MINRAMNT        0
MINRDATE        0
MAXRAMNT        0
MAXRDATE        0
LASTGIFT        0
LASTDATE        0
FISTDATE        0
NEXTDATE     9973
TIMELAG      9973
AVGGIFT         0
CONTROLN        0
TARGET_B        0
TARGET_D        0
HPHONE_D        0
RFA_2F          0
CLUSTER2      132
dtype: int64

In [5]:
#Use appropriate methods to clean the columns GEOCODE2, WEALTH1, ADI, DMA,and MSA.
#Use appropriate EDA technique where ever necessary.

In [6]:
df['GEOCODE2'].value_counts()

A    34484
B    28505
D    16580
C    15524
       187
Name: GEOCODE2, dtype: int64

In [7]:
df['GEOCODE2'].fillna('O', inplace=True)
df['GEOCODE2'].value_counts()

A    34484
B    28505
D    16580
C    15524
       187
O      132
Name: GEOCODE2, dtype: int64

In [8]:
df['GEOCODE2'] = df['GEOCODE2'].replace('O', 'Other')
df['GEOCODE2'].value_counts()

A        34484
B        28505
D        16580
C        15524
           187
Other      132
Name: GEOCODE2, dtype: int64

In [9]:
#df['WEALTH1'].value_counts()

In [10]:
#df['ADI'].value_counts()

In [11]:
#df['DMA'].value_counts()

In [12]:
#df['MSA'].value_counts()

In [13]:
#df['GEOCODE2'].isna().sum()

In [14]:
#df['WEALTH1'].isna().sum()

In [15]:
#df['ADI'].isna().sum()

In [16]:
#df['DMA'].isna().sum()

In [17]:
#df['MSA'].isna().sum()

In [18]:
#new_df=df[['WEALTH1','DMA','MSA','ADI']]

In [19]:
#new_df.hist(figsize=(15,12),bins=40)

In [20]:
#from sklearn.impute import KNNImputer

In [21]:
#imputer = KNNImputer(n_neighbors=5, weights='uniform', metric='nan_euclidean')
#imputer.fit(new_df)

In [22]:
#new_df2 = imputer.transform(new_df)

In [23]:
#new_df3=pd.DataFrame(new_df2, columns=new_df.columns)

In [24]:
#new_df3

In [25]:
#new_df3.isna().sum()